---
deployment:
  tasks:
    - export HOME=/home/moodyfil
    - export PATH=/home/moodyfil/nodevenv/moodyfilm/20/bin:/opt/alt/alt-nodejs20/root/usr/bin:$PATH
    - source /home/moodyfil/nodevenv/moodyfilm/20/bin/activate
    - npm install --include=dev
    - npm run build
    - mkdir -p tmp
    - touch tmp/restart.txt
